export const variables = {
    colorAccent: ['accent', 1],
    colorDark: '#455A64',
    foreground: ['foreground', 1],
    background: ['background', 1],
    fontSizeSm: 11,
    fontSizeMd: 12,
    fontSizeLg: 14,
    fontSizeHuge: 24,
    fontFace: 'system',
    kindFontFace: 'system',
    kindFontSize: 'var(fontSizeLg)',
    buttonBackground: ['background', 0.5],
    buttonBackgroundHover: 'color(var(colorAccent) a(0.2))',
    buttonMinSize: [80, 28],
    buttonIconFileColor: 'color(var(colorAccent) a(0.70))',
    buttonIconFileSelectedColor: 'var(colorAccent)',
    buttonIconFileBackground: 'var(background)',
    buttonIconFileSelectedBackground: 'var(buttonIconFileBackground)',
    buttonIconFileContentMargin: [12, 12],
    autoCompleteFontSize: 'var(fontSizeSm)',
    autoCompleteRowPadding: [10, 6],
    autoCompleteFontItalic: true,
    autoCompleteColor: ['foreground', 0.5],
    autoCompleteMatchColor: 'var(colorAccent)',
    autoCompleteSelectedColor: 'var(foreground)',
    autoCompleteSelectedMatchColor: 'var(colorAccent)',
    autoCompleteBlend: true,
    autoCompleteSelectedBackground: ['foreground', 0.1],
    panelControlBackground: 'var(background)',
    panelPathRowFontSize: 'var(fontSizeSm)',
    panelPathRowFontItalic: true,
    panelPathRowColor: 'var(foreground)',
    panelRowPadding: [10, 10],
    panelRowFontSize: 'var(fontSizeMd)',
    panelRowBackground: 'var(background)',
    panelRowColor: 'color(var(colorDark) l(+ 20%))',
    panelRowSelectedBackground: ['foreground', 0.1],
    panelRowSelectedColor: 'var(foreground)',
    panelRowMatchColor: 'var(colorAccent)',
    panelRowSelectedMatchColor: 'var(colorAccent)',
    inputBackground: 'var(background)',
    inputBorderColor: ['foreground', 0.1],
    inputBorderSize: [0, 0, 0, 1],
    inputBorderMargin: [12, 8, 12, 8],
    sidebarBackground: 'var(background)',
    sidebarHeadingFontSize: 'var(fontSizeSm)',
    sidebarLabelFontSize: 'var(fontSizeMd)',
    sidebarLabelPadding: [14, 3],
    sidebarIndent: 20,
    sidebarIndentOffset: 14,
    sidebarLabelColor: 'color(var(colorDark) l(+ 20%))',
    sidebarLabelColorHover: 'var(foreground)',
    sidebarLabelSelectedBackground: ['foreground', 0.06],
    sidebarLabelSelectedColor: 'var(colorAccent)',
    sidebarLabelExpandableColor: 'var(colorAccent)',
    sidebarLabelSelectedBorderSize: [2, 0, 0, 0],
    sidebarLabelSelectedBorderColor: 'var(colorAccent)',
    sidebarIconFolderColor: 'var(sidebarLabelColor)',
    sidebarIconFolderExpandedColor: 'var(sidebarLabelExpandableColor)',
    sidebarIconFileSize: 7,
    statusbarBackground: 'var(background)',
    statusbarLabelColor: 'color(var(colorDark) l(+ 20%))',
    statusbarIconColor: 'var(statusbarLabelColor)',
    statusbarLabelBold: false,
    statusbarLabelFontSize: 'var(fontSizeSm)',
    statusbarMargin: [10, 4, 0, 4],
    tabBold: false,
    tabFontSize: 'var(fontSizeSm)',
    tabColor: ['foreground', 0.5],
    tabBackground: 'var(background)',
    tabBackgroundSheetModifier: 'blend(var(colorAccent) 95%)',
    tabSelectedBorderColor: 'var(colorAccent)',
    tabSelectedBorderSize: [0, 0, 0, 2],
    tabSelectedColor: 'var(foreground)',
    tabDiffIconColor: 'var(colorAccent)',
    tabDiffColor: 'var(--bluish)',
    tabDiffItalic: true,
    tabHeight: 45,
    tabWidth: 50,
    tabMargin: 0,
    tabNavigationColor: 'var(foreground)',
    tabMoreColor: 'var(foreground)',
    tabCloseColor: ['foreground', 0.5],
    tabCloseSelectedColor: 'var(foreground)',
    tabCloseHoverColor: 'var(colorAccent)',
    titleBarBackground: 'var(background)',
    titleBarColor: 'color(var(colorDark) l(+ 20%))',
    tooltipBackground: 'var(foreground)',
    tooltipLabelColor: 'var(background)',
    gridLayoutBorderColor: 'color(var(colorAccent) blenda(var(colorDark) 30%))',
    gridLayoutBorderSize: 2,
    minimapColor: 'color(var(colorAccent) a(0.2))',
    minimapOpacity: '0.5',
    scrollBar: ['foreground', 0.2],
    scrollTrack: ['foreground', 0.4],
    vcsBadgeSize: 5,
    vcsIgnored: 'color(var(sidebarLabelColor) a(0.5))',
    vcsModified: 'var(--redish)',
    vcsUnmerged: 'var(--bluish)',
    vcsDeleted: 'var(--bluish)',
    vcsStaged: 'var(--yellowish)',
    vcsUntracked: 'var(--greenish)',
    vcsMissing: 'var(--orangish)',
};
