module.exports = {
    foreground: "var(foreground)",
    background: "var(background)",
    caret: "var(cursor)",
    block_caret: "var(cursor)",
    line_highlight: "color(var(foreground) alpha(0.1))",
    selection: "color(var(foreground) alpha(0.10))",
    selection_border: "var(cyan)",
    inactive_selection: "color(var(cyan) alpha(0.1))",
    misspelling: "var(red)",
    shadow: "color(var(background) alpha(0.5))",
    gutter_foreground: "color(var(foreground) alpha(0.2))",
    active_guide: "var(cyan)",
    stack_guide: "var(orange)",
    fold_marker: "var(yellow)",
    highlight: "var(pink)",
    find_highlight: "var(yellow)",
    find_highlight_foreground: "var(background)",
    line_diff_width: "2",
    line_diff_added: "var(diffAdded)",
    line_diff_modified: "var(diffModified)",
    line_diff_deleted: "var(diffDeleted)"
}
